import React, { createContext, useState, useContext } from 'react';

// 📊 A FELÜLET STATIKUS SZÓTÁRA
// Ide gyűjtjük a gombok, feliratok fix szövegeit. Nyugodtan bővíthetjük később!
const translations = {
  hu: {
    // Navigációs fülek (WeeklyChallengeView)
    tabChallenges: '🏆 Kihívások',
    tabUpcoming: '⏳ Közelgő ligák',
    tabPast: '📜 Befejezett ligák',
    tabAlbum: '🖼️ Képcsarnok',
    tabStats: '🏆 Dicsőségfalam',
    tabHof: '👑 Mesterek csarnoka',
    btnRules: '📖 Játékszabályok & Rangok',
    
    // Kártya feliratok
    typeBlitz: '🔴 Villámfutam',
    typeMaster: '🔵 Mesterfutam',
    statusMaster: '🚀 Képmester vagy',
    statusEntered: '🚀 Neveztél',
    statusNotEntered: '⏳ Még nem neveztél',
    timeLeft: '⏳ Hátralévő idő:',
    photographers: 'fotós',
    unvoted: 'értékelendő',
    loading: '⏳ Betöltés...',

    // 🎯 ÚJ: FEJLÉC / MENÜPONTOK
    navHome: '🏠 Főoldal',
    navArena: '🏆 Mesterek ligája',
    navContests: '📝 Pályázatok',
    navClub: '👥 Fotóklub',
    navInternational: '🌐 Nemzetközi szalonok',
    navMap: '🌍 Helyszínek',
    navAdmin: '⚙️ Admin',
    
    // Pályázatok almenü
    subClubContests: 'Klubom aktív pályázatai',
    subOpenContests: 'Nyílt aktív pályázatok',
    subClosedContests: 'Lezárult pályázatok',
    
    // Fotóklub almenü
    subClubNews: 'Klub Hírek',
    subClubNights: 'Klubestek',
    subClubHomeworks: 'Házi feladatok',
    
    // Nemzetközi almenü
    subSalonsList: '🌐 Szalonok listája',
    subFiap: '🏅 FIAP Követő',
    subMafosz: 'MAFOSZ Követő',
    
    // Admin almenü
    subLeaderClub: '🛡️ Klubom adatai',
    subManageContests: 'Pályázatok kezelése',
    subManageMeetings: 'Klubestek kezelése',
    subManageHomeworks: 'Házi feladatok kezelése',
    subManageWeekly: 'Kihívások kezelése',
    subManageSettings: 'Kategóriák és Díjak',
    subManageSalons: 'Szalonok kezelése',
    subManageUsers: 'Felhasználók',
    subManageClubs: 'Fotóklubok',
    
    // Felhasználói fiók almenü
    subProfile: '👤 Profilom',
    subPortfolio: '🖼️ Saját Portfólió',
    subPackages: '💎 Tárhelycsomagom',
    subSupport: '✉️ Support & Segítség',
    subLogout: '🚪 Kijelentkezés',

    dashWelcome: 'Üdvözlünk',
    dashSupportNotice: 'Ha valami nem megfelelően működik, a support részen kapcsolatba léphetsz a fejlesztővel!',
    dashPremiumBadge: '⭐ Aktív Prémium Tag',
    dashAlertsTitle: '🔔 Aktuális Események & Értesítések',
    dashSyncing: '⏳ Adatok szinkronizálása a szerverrel...',
    dashSyncNotice: '(Ha régen voltál itt, a szerver felébresztése eltarthat pár másodpercig)',
    dashAlertsError: '❌ Nem sikerült betölteni az értesítéseket.',
    dashReload: 'Újratöltés',
    dashNewNews: 'Új Klub Hír!',
    dashLocation: 'Helyszín',
    dashHomework: 'Házi feladat',
    dashActiveContest: 'Aktív Pályázat',
    dashNoAlerts: 'Jelenleg nincs új értesítésed vagy határidős feladatod. Nyugalom van! ☕',

    tileWeeklyTitle: 'Kihívások',
    tileWeeklyDesc: 'Tölts fel az aktuális napi, vagy heti témában, szavazz mások képeire és kerülj a toplista élére!',
    tileContestsTitle: 'Nyílt Pályázatok',
    tileContestsDesc: 'Vegyél részt a közösségi vagy zártkörű házi fotópályázatokon.',
    tilePortfolioTitle: 'Saját Portfólió',
    tilePortfolioDesc: 'Töltsd fel és menedzseld a saját fotóidat, nézd meg az eredményeidet, vagy akár kérj AI elemzést.',
    tileMapTitle: 'Fotós Helyszínek',
    tileMapDesc: 'Fedezz fel új fotós helyeket a térképen, vagy oszd meg a sajátjaidat!',
    tileProgressTitle: 'Minősítések (FIAP/MAFOSZ)',
    tileProgressDesc: 'Kövesd nyomon az elfogadásaidat, generálj FIAP kompatibilis Excel táblát.',
    tileSalonsTitle: 'Nemzetközi Szalonok',
    tileSalonsDesc: 'Böngéssz az aktuális FIAP, MAFOSZ, PSA, vagy klub szalonok között, nevezd be a fotóidat pályázatokra.',
    tileClubTitle: 'Fotóklub Élet',
    tileClubDesc: 'Klubestek, találkozók, feladatok, vagy klub portfólió válogatás egy helyen.',
    tileAdminTitle: 'Adminisztráció',
    tileAdminDesc: 'Pályázatok, klubestek, felhasználók és szalonok kezelése.',

    // === HU BLOKK ALJA ===
    profTitle: '👤 Személyes adatok',
    profNotice: 'Ez a név fog megjelenni a leadott pályaműveid mellett, a dicsőségfalon és az okleveleken is.',
    profLabelName: 'Megjelenített név',
    profPlaceholderName: 'Teljes neved',
    profSaving: 'Módosítás mentése...',
    profSaveBtn: 'Változtatások Mentése 💾',
    profClubTitle: '🛡️ Fotóklub tagság beállítása',
    profClubPending: 'Csatlakozási kérelem elküldve a(z) {club} klubhoz. A klub vezetőjének vagy helyettesének jóváhagyására várunk. Addig a belső felületek zárolva maradnak.',
    profClubActive: '✓ Aktív tagja vagy a(z) {club} fotóklubnak ({role} rangban).',
    profClubNone: 'Jelenleg nem tartozol egyetlen klubhoz sem. Válassz az alábbi, aktív vezetőséggel rendelkező klubok közül!',
    profSelectClub: '-- Válassz fotóklubot --',
    profSendRequest: 'Csatlakozási kérelem elküldése ✉️',
    profLeaderTitle: '👑 Tagfelvételi Kérelmek',
    profLeaderNotice: 'Az alábbi fotósok szeretnének csatlakozni a klubodhoz. Az elbírálás után azonnali hozzáférést kapnak.',
    profNoPending: 'Nincs függőben lévő jelentkezés.',
    profApprove: 'Befogadás ✓',
    profReject: 'Elutasítás',
    roleLeader: 'Klubvezető',
    roleDeputy: 'Helyettes',
    roleMember: 'Klubtag',
    // Rendszerüzenetek
    msgEmptyName: 'A név mező nem maradhat üresen!',
    msgSameName: 'Ez a név megegyezik a jelenlegi neveddel.',
    msgNameSuccess: '🎯 Megjelenített név sikeresen átírva!',
    msgNameError: 'Hiba történt a név mentése közben.',
    msgNetworkError: 'Hálózati hiba történt.',
    msgSelectClubError: 'Kérlek válassz egy fotóklubot!',
    msgRequestSent: '✉️ Kérelem elküldve a vezetőségnek!',
    msgApproveConfirm: 'Befogadod a tagot a klubba?',
    msgRejectConfirm: 'Biztosan elutasítod a jelentkezést?',
    msgApproveSuccess: '✅ Tag sikeresen felvéve!',
    msgRejectSuccess: '❌ Jelentkezés elutasítva.',

    // === HU BLOKK ALJA ===
    helpTitle: '📖 Útmutató a Mesterek Ligájához',
    helpExposureTitle: '⚡ Láthatósági Mérő (Az Expozíciós Energia)',
    helpExposureDesc: 'Amikor feltöltöd a képed, expozíciós energiát kapsz. Valahányszor a gép megmutatja a fotódat valakinek értékelésre, ez az energia csökken. Új energiát úgy szerezhetsz, ha te is pontozol más alkotásokat. Tartsd a mérőt a Zöld zónában!',
    helpJokerTitle: '🃏 Joker: Taktikai Képcsere',
    helpJokerDesc: 'Úgy érzed, jobb fotót is tudnál mutatni az adott témában? Minden kihívásban ugyanazzal a Joker ponttal szabadon cserélgetheted a képeidet az Aréna Képtáradból vagy a galériádból! Az új fotód 0 pontról indul, de a régit bármikor büntetés nélkül visszahozhatod.',
    helpMasterTitle: '👑 Ki az a Témavezető Képmester?',
    helpMasterDesc: 'Minden kihívásnak van egy kijelölt Képmestere, aki a forduló szakmai házigazdája. Mivel ő felügyeli a válogatást, saját alkotással nem indulhat az adott futamban. Cserébe kap 5 darab exkluzív Mester-szavazatot, amelyek egyenként fixen +10 pontot érnek, így kiemelt szerepe van a legszebb képek felemelésében!',
    helpRewardsTitle: '🏆 Dobogós Nyeremények & Extra Cserék',
    helpRewardsDesc: 'A futamok lezárulásakor a mezőny legkiemelkedőbb fotóművészei értékes globális Joker cseréket és exkluzív hozzáférést kapnak jutalmul:',
    helpReward1: '1. Helyezett (Győztes):',
    helpReward1Bonus: '+3 db globális Joker csere + 1 HÉTTEL MEGHOSSZABBÍTOTT PRÉMIUM TAGSÁG teljesen ingyen!',
    helpReward2: '2. Helyezett:',
    helpReward2Bonus: '+2 db Joker csere',
    helpReward3: '3. Helyezett:',
    helpReward3Bonus: '+1 db Joker csere',
    helpRanksTitle: '⭐ Ranglétra és Szavazati Erő',
    helpRanksDesc: 'Ahogy fejlődik a látásmódod, úgy növekszik a szavazati erőd is! Minél magasabb rangot érsz el a pontjaid és győzelmeid alapján, annál nagyobb súllyal bír a szavazatod mások képein. 💡 Minden szintlépésért a rendszer azonnal +10 db ajándék Joker cserével jutalmaz meg!',
    helpYou: 'TE VAGY',

    // === HU BLOKK ALJA ===
    roomChallengeRoom: 'Kihívás szoba',
    roomMasterTitle: '👑 Képmester:',
    roomMainPrize: 'FŐDÍJ AZ 1. HELYÉRT:',
    roomFreePremium: '1 HÉTTEL MEGHOSSZABBÍTOTT PRÉMIUM TAGSÁG',
    roomBonusSwaps: '+ 3 db Joker Csere! 💎',
    roomTimeLeft: 'Hátralévő Idő',
    roomCalculating: 'Számítás...',
    roomExposureMeter: 'Láthatósági Mérő',
    roomExpNoEntry: 'Töltsd fel a képedet az induláshoz, és kapsz 10 alap energiát!',
    roomExpNewPhotos: '⚡ Új fotó érkezett az Arénába (vagy valaki Jokert használt)! Értékelj, hogy a mérőd újra maxon pörögjön!',
    roomExpMaxed: '🔥 A képed a maximumon pörög! Jelenleg nincs több értékelhető kép az Arénában.',
    roomVotingArena: '⚔️ Értékelő Aréna',
    roomNoVoteRight: 'Nincs szavazati jogod!',
    roomNoVoteRightDesc: 'A küzdelembe való belépéshez először be kell nevezned egy saját fotóval!',
    roomAllVoted: 'Mindent értékeltél!',
    roomAllVotedDesc: 'Várj, amíg a többiek is töltenek fel új képeket.',
    roomOffTopicWarning: '⚠️ {count} játékos szerint ez a kép Off-Topic vagy AI generált!',
    roomMasterVoteBtn: '👑 Képmester Különdíj (+10 pont)',
    roomMasterVotesRemaining: 'Még {count} db szavazatod maradt',
    roomVoteSuper: '✨ Szuper',
    roomPoints: ' pont',
    roomVoteBrilliant: '🔥 Zseniális',
    roomVotePass: '⏭️ Nem tetszik (0 pont)',
    roomReportBtn: '⚠️ Off-Topic/AI gyanús Jelentés',
    roomLoadingPhoto: 'Kép betöltése...',
    roomMyEntry: '📸 Saját Nevezésem',
    roomJokerSwaps: 'Joker cserék: {count} db',
    roomYouAreMaster: 'Te vagy a Képmester!',
    roomYouAreMasterDesc: 'Ebben a futamban te lettél felkérve a képmesternek! Saját alkotással nem nevezhetsz, cserébe kapsz 5 darab, egyenként +10 pontot érő Különdíjat, amit a szavazás során oszthatsz szét a kedvenc képeid között.',
    roomResult: 'Eredmény',
    roomViews: 'Nézettség',
    roomMyOffTopicTitle: '🚫 Figyelmeztetés: Tématévesztés gyanúja!',
    roomMyOffTopicDesc: 'A képedet eddig {count} fotóstársad jelentette off-topicnak vagy gyanúsan AI-al generáltnak. Kérlek ügyelj a pontos témára, illetve ne használj AI fotót!',
    roomSwapTitle: '🔄 Új Fotó Feltöltése & Csere',
    roomSwapDesc: 'Rosszul megy a szekér? Tölts fel egy vadonatúj fotót 1 cserepontért! Az új kép 0 pontról indul, de a mostani képedet sem veszíted el.',
    roomSwappingInProgress: 'Csere folyamatban...',
    roomSwapBrowseBtn: 'Joker Elköltése Tallózással 🔄',
    roomOrUseAlbum: 'VAGY elhasználhatsz 1 Jokert egy már meglévő albumképedre:',
    roomLoadingGallery: '⏳ Képtár betöltése...',
    roomSwapGalleryBtn: '🖼️ Joker Csere az Aréna Képtárból',
    roomNoSwapsLeft: '🔒 Elfogytak a globális Joker cseréid! Teljesíts jól feladatokat extra pontokért.',
    roomPastEntriesTitle: '↩️ Korábbi fotóid ebben a fordulóban',
    roomPastSavedScore: 'Eltárolt korábbi állás:',
    roomReactivateBtn: '↩️ Visszaaktiválás',
    roomUploadingInProgress: 'Feltöltés...',
    roomUploadSubmitBtn: 'Nevezés és Indulás 🚀',
    roomOrChooseAlbumUpload: 'VAGY választhatsz egy meglévő fotót az albumodból:',
    roomChooseGalleryUploadBtn: '🖼️ Választás az Aréna Képtárból',
    roomClubLeague: '🛡️ Klubok Ligája',
    roomLiveBadge: 'ÉLŐ',
    roomClubLeagueDesc: 'A 3 legjobb klubtag megmérettetése alapján.',
    roomNoClubsYet: 'Még nincs rangsorolt klub.',
    roomActiveMembers: 'aktív tag',
    roomBlindLeaderboard: '🏆 Vak Toplista',
    roomBlindLeaderboardDesc: 'A taktikázás elkerülése végett az ellenfelek kiléte titkos!',
    roomArenaEmpty: 'Még üres az Aréna.',
    roomEncryptedOpponent: 'Titkosított ellenfél',
    roomMe: 'Én',

    // === HU BLOKK ALJA ===
    planTitle: '📜 Új Kihívás Javaslata',
    planDesc: 'Vázold fel a kihívást! Jóváhagyás után, a javaslatod bekerül a hivatalos közelgő kihívások közé.',
    planLabelTitle: 'Kihívás megnevezése (Téma) *',
    planPlaceholderTitle: 'Pl.: Vadvizek moraja, Városi sziluettek',
    planLabelDesc: 'Hadparancs (Részletes leírás & Megkötések) *',
    planPlaceholderDesc: 'Milyen kompozíciókat vársz? Mit tilos használni?',
    planLabelStart: 'Kezdés dátuma *',
    planLabelEnd: 'Zárás dátuma *',
    planLabelMaster: 'Kijelölt Képmester',
    planPlaceholderMaster: 'Pl.: Csontos Mária',
    planLabelAuthor: 'Borítókép készítője',
    planPlaceholderAuthor: 'Pl.: János Lakatos',
    planLabelCover: 'Borítókép kiválasztása',
    planPreviewAlt: 'Elölnézet',
    planSubmitting: 'Haditerv küldése...',
    planSubmitBtn: 'Haditerv beküldése Törzsi bírálatra ⚔️',
    msgFillAllFields: 'Minden kötelező mezőt tölts ki!',
    msgProposalSuccess: '⚔️ Haditerv sikeresen benyújtva bírálatra!',
    msgProposalError: 'Hiba történt a küldés során.',

    // === HU BLOKK ALJA ===
    hofLoading: '⏳ A pódium összeállítása...',
    hofEmpty: 'Még egyetlen fotós sem gyűjtött pontot. Legyél te az első!',
    hofTitle: '👑 Globális Fotós Dicsőségfal',
    hofDesc: 'A közösség összesített ranglistája az éles és lezárult arénákban gyűjtött csillagok alapján.',
    hofYou: 'TE VAGY',

    // === HU BLOKK ALJA ===
    archiveTitle: '📜 Befejezett Kihívások',
    archiveNotice: 'Az eredményeknél a képre kattintva likeolhatod, vagy hozzászólhatsz a fotóhoz',
    archiveEmpty: 'Nincs lezárt küzdelem.',
    archiveCoverAuthor: '📸 Borítókép készítője: ',
    archiveClubLeague: '🛡️ Klubok Ligája Eredmény',
    archiveBlitz: 'Villámfutam',
    archiveMaster: 'Mesterfutam',
    archiveClubLeagueDesc: 'A 3 legjobb játékos teljesítménye alapján.',
    archiveNoClubs: 'Ebben a futamban nem mérkőztek meg szövetségek.',
    archiveSelectChallenge: 'Válassz egy futamot a bal oldali listából.',
    archiveUnknownClub: 'Ismeretlen Klub',
    archiveBasedOnPoints: ' fotós pontjai alapján',
    archiveMemberIndividualScore: '📊 Klubjátékosok ({count} fő)',
    archiveNoMemberPoints: 'Nem szerzett pontot senki ebből a klubból.',
    archiveIndividualRanking: '🏅 Egyéni Rangsor',
    archiveSelectMatch: 'Válassz egy futamot az eredmények megjelenítéséhez.',
    archivePhotographer: 'Fotós',
    archivePostPraises: ' utólagos dicséret',
    archiveNomadWarrior: 'Nomád harcos',

    // === HU BLOKK ALJA ===
    trophyLoading: '⏳ Statisztikák betöltése...',
    trophyError: 'Nem sikerült betölteni az adatokat.',
    trophyCurrentStatus: 'Jelenleg Státuszod',
    trophyLegendMax: 'Elérted a legmagasabb rangot! Te vagy a klub Vizuális Legendája! 👑',
    trophyNextLevelPoints: 'Még {points} pont szükséges a következő szinthez!',
    trophyNextLevelWins: '🔒 Megvannak a pontjaid, de még {wins} db Aréna Győzelem (🥇) szükséges a szintlépéshez!',
    trophyNextLevelReady: 'Gratulálunk! Minden feltétel teljesítve a szintlépéshez!',
    trophyPremiumActive: 'Aktív Győzelmi Prémium Tagság!',
    trophyPremiumDesc: 'Az Aréna bajnokaként a korlátlan prémium kiváltságaid biztosítva vannak egészen eddig: ',
    trophyPremiumNotice: ' (Nem igényel bankkártyát).',
    trophyStatTotalPoints: 'Összes Szerzett Pont',
    trophyStatWins: 'Aréna Győzelem (🥇)',
    trophyStatPodiums: 'Dobogós (2-3. hely)',
    trophyStatJokers: 'Elkölthető Joker Csere',
    trophyStatViews: 'Összes Megtekintés',
    trophyInviteTitle: '🎁 Hívj meg egy barátot!',
    trophyInviteDesc: 'Oszd meg a kódodat egy fotós ismerősöddel! Ha regisztrál a portálra ÉS megadja a kódod, te azonnal +10 db Joker cserét kapsz a globális egyenlegedhez.',
    trophyInviteCode: 'KÓDOD:',
    trophyCopy: 'Másolás',
    trophyCopiedAlert: '📋 Meghívó kód a vágólapra másolva!',
    trophyReferredTitle: '🤝 Téged ki hívott meg?',
    trophyReferredDesc: 'Ha egy barátod ajánlására regisztráltál a Fotóklub Portálra, add meg az ő személyes kódját, hogy megkapja érte a megérdemelt jutalom cseréit!',
    trophyReferredSuccess: '✓ Sikeresen rögzítetted a meghívásodat! Köszönjük.',
    trophySubmit: 'Beküldés',
    trophyPlaceholderRef: 'Pl.: REF-A1B2C3',
    trophyPastEntries: '📸 Korábbi Pályaművek ({count})',
    trophyNoPastEntries: 'Még nincs befejezett kihívásod!',
    trophyNoPastEntriesDesc: 'Vegyél részt a kihívásokban, és itt fognak megjelenni a korábbi eredményeid.',
    trophyBadge1st: '🥇 1. Hely',
    trophyBadgePodium: '🏆 Dobogós (2-3.)',
    trophyField: 'Mezőny: {count} kép',
    trophyRankLabel: 'Helyezés: ',
    trophyShareBtn: '🚀 Eredmény megosztása',
    trophyPointsUnit: ' pont',

    // === HU BLOKK ALJA ===
    modalUploadTitle: '🖼️ Nevezés az Aréna Képtáradból',
    modalSwapTitle: '🃏 Válaszd ki a Joker Fotódat',
    modalUploadDesc: 'Melyik meglévő galériás fotóddal szeretnél benevezni a mostani futamra?',
    modalSwapDesc: 'Melyik galériás képedet küldöd harcba? A kék keretes Visszacserék megtartják a fordulóban korábban szerzett csillagaikat!',
    modalBadgeSwapBack: '↩️ Visszacsere',
    msgUploadConfirm: 'Biztosan ezzel a meglévő képeddel nevezel be a küzdelembe?',
    msgUploadSuccess: '🎉 Sikeres nevezés az albumból!',
    msgUploadError: 'Hiba a nevezés során.'
  },

  
  en: {
    // Navigációs fülek (WeeklyChallengeView)
    tabChallenges: '🏆 Challenges',
    tabUpcoming: '⏳ Upcoming Leagues',
    tabPast: '📜 Past Leagues',
    tabAlbum: '🖼️ Photo Arena',
    tabStats: '🏆 My Trophies',
    tabHof: '👑 Hall of Fame',
    btnRules: '📖 Rules & Ranks',
    
    // Kártya feliratok
    typeBlitz: '🔴 Blitz Match',
    typeMaster: '🔵 Master Match',
    statusMaster: '🚀 You are the Master',
    statusEntered: '🚀 Entered',
    statusNotEntered: '⏳ Not Entered Yet',
    timeLeft: '⏳ Time Left:',
    photographers: 'photographers',
    unvoted: 'to review',
    loading: '⏳ Loading...',

    // 🎯 ÚJ: FEJLÉC / MENÜPONTOK ANGOLUL
    navHome: '🏠 Home',
    navArena: '🏆 Masters League',
    navContests: '📝 Contests',
    navClub: '👥 Photo Club',
    navInternational: '🌐 Intl. Salons',
    navMap: '🌍 Map Spots',
    navAdmin: '⚙️ Admin',
    
    // Pályázatok almenü
    subClubContests: 'My Club Active Contests',
    subOpenContests: 'Open Active Contests',
    subClosedContests: 'Closed Contests',
    
    // Fotóklub almenü
    subClubNews: 'Club News',
    subClubNights: 'Club Nights',
    subClubHomeworks: 'Homeworks',
    
    // Nemzetközi almenü
    subSalonsList: '🌐 Salons List',
    subFiap: '🏅 FIAP Tracker',
    subMafosz: 'MAFOSZ Tracker',
    
    // Admin almenü
    subLeaderClub: '🛡️ My Club Data',
    subManageContests: 'Manage Contests',
    subManageMeetings: 'Manage Club Nights',
    subManageHomeworks: 'Manage Homeworks',
    subManageWeekly: 'Manage Challenges',
    subManageSettings: 'Categories & Awards',
    subManageSalons: 'Manage Salons',
    subManageUsers: 'Users',
    subManageClubs: 'Photo Clubs',
    
    // Felhasználói fiók almenü
    subProfile: '👤 My Profile',
    subPortfolio: '🖼️ My Portfolio',
    subPackages: '💎 My Storage',
    subSupport: '✉️ Support & Help',
    subLogout: '🚪 Logout',

    dashWelcome: 'Welcome',
    dashSupportNotice: 'If something is not working properly, you can contact the developer in the support section!',
    dashPremiumBadge: '⭐ Active Premium Member',
    dashAlertsTitle: '🔔 Current Events & Notifications',
    dashSyncing: '⏳ Syncing data with the server...',
    dashSyncNotice: '(If you haven\'t been here in a while, waking up the server might take a few seconds)',
    dashAlertsError: '❌ Failed to load notifications.',
    dashReload: 'Reload',
    dashNewNews: 'New Club News!',
    dashLocation: 'Location',
    dashHomework: 'Homework',
    dashActiveContest: 'Active Contest',
    dashNoAlerts: 'You currently have no new notifications or deadline tasks. All quiet! ☕',

    // Főoldal Csempék EN
    tileWeeklyTitle: 'Challenges',
    tileWeeklyDesc: 'Upload for the current daily or weekly theme, vote on others\' photos, and reach the top of the leaderboard!',
    tileContestsTitle: 'Open Contests',
    tileContestsDesc: 'Participate in community or private local photo contests.',
    tilePortfolioTitle: 'My Portfolio',
    tilePortfolioDesc: 'Upload and manage your own photos, view your results, or even request an AI analysis.',
    tileMapTitle: 'Photo Locations',
    tileMapDesc: 'Discover new photography spots on the map or share your own!',
    tileProgressTitle: 'Distinctions (FIAP/MAFOSZ)',
    tileProgressDesc: 'Track your acceptances and generate a FIAP-compatible Excel sheet.',
    tileSalonsTitle: 'International Salons',
    tileSalonsDesc: 'Browse through current FIAP, MAFOSZ, PSA, or club salons, and enter your photos into contests.',
    tileClubTitle: 'Photo Club Life',
    tileClubDesc: 'Club nights, meetings, tasks, or club portfolio selections all in one place.',
    tileAdminTitle: 'Administration',
    tileAdminDesc: 'Manage contests, club nights, users, and salons.',

    // === EN BLOKK ALJA ===
    profTitle: '👤 Personal Data',
    profNotice: 'This name will appear next to your submitted entries, on the wall of fame, and on certificates as well.',
    profLabelName: 'Display Name',
    profPlaceholderName: 'Your full name',
    profSaving: 'Saving changes...',
    profSaveBtn: 'Save Changes 💾',
    profClubTitle: '🛡️ Photo Club Membership Settings',
    profClubPending: 'Join request sent to {club} photo club. Waiting for approval from the club leader or deputy. Until then, internal pages remain locked.',
    profClubActive: '✓ You are an active member of {club} photo club (Role: {role}).',
    profClubNone: 'You currently do not belong to any club. Choose from the active clubs below!',
    profSelectClub: '-- Choose a photo club --',
    profSendRequest: 'Send Join Request ✉️',
    profLeaderTitle: '👑 Membership Applications',
    profLeaderNotice: 'The photographers below want to join your club. They will get instant access after approval.',
    profNoPending: 'No pending applications.',
    profApprove: 'Accept ✓',
    profReject: 'Reject',
    roleLeader: 'Club Leader',
    roleDeputy: 'Deputy',
    roleMember: 'Club Member',
    // System messages
    msgEmptyName: 'The name field cannot be empty!',
    msgSameName: 'This name is identical to your current name.',
    msgNameSuccess: '🎯 Display name successfully updated!',
    msgNameError: 'An error occurred while saving the name.',
    msgNetworkError: 'A network error occurred.',
    msgSelectClubError: 'Please select a photo club!',
    msgRequestSent: '✉️ Request sent to the leadership!',
    msgApproveConfirm: 'Do you want to accept this member into the club?',
    msgRejectConfirm: 'Are you sure you want to reject this application?',
    msgApproveSuccess: '✅ Member successfully accepted!',
    msgRejectSuccess: '❌ Application rejected.',

    // === EN BLOKK ALJA ===
    helpTitle: '📖 Guide to the Masters League',
    helpExposureTitle: '⚡ Exposure Meter (Exposure Energy)',
    helpExposureDesc: 'When you upload your photo, you receive exposure energy. Every time the system shows your photo to someone for review, this energy decreases. You can gain new energy by voting on others\' work. Keep the meter in the Green zone!',
    helpJokerTitle: '🃏 Joker: Tactical Photo Swap',
    helpJokerDesc: 'Feel like you could show a better photo for the given theme? In every challenge, you can freely swap your pictures from your Arena Gallery or device using the same Joker point! Your new photo starts from 0 points, but you can bring the old one back at any time without penalty.',
    helpMasterTitle: '👑 Who is the Challenge Master?',
    helpMasterDesc: 'Every challenge has a designated Challenge Master, who serves as the professional host of the round. Since they oversee the selection, they cannot participate with their own work in that specific match. In return, they receive 5 exclusive Master votes, each worth a fixed +10 points, playing a key role in elevating the most beautiful images!',
    helpRewardsTitle: '🏆 Podium Prizes & Extra Swaps',
    helpRewardsDesc: 'At the end of each match, the most outstanding photographers in the field receive valuable global Joker swaps and exclusive access as a reward:',
    helpReward1: '1st Place (Winner):',
    helpReward1Bonus: '+3 global Joker swaps + 1 WEEK EXTENDED PREMIUM MEMBERSHIP completely free!',
    helpReward2: '2nd Place:',
    helpReward2Bonus: '+2 Joker swaps',
    helpReward3: '3rd Place:',
    helpReward3Bonus: '+1 Joker swap',
    helpRanksTitle: '⭐ Rank Ladder and Voting Power',
    helpRanksDesc: 'As your vision develops, your voting power grows too! The higher rank you achieve based on your points and victories, the more weight your vote carries on others\' photos. 💡 For every level up, the system instantly rewards you with +10 free bonus Joker swaps!',
    helpYou: 'YOU',

    // === EN BLOKK ALJA ===
    roomChallengeRoom: 'Challenge Room',
    roomMasterTitle: '👑 Challenge Master:',
    roomMainPrize: 'MAIN PRIZE FOR 1ST PLACE:',
    roomFreePremium: '1 WEEK EXTENDED PREMIUM MEMBERSHIP',
    roomBonusSwaps: '+ 3 Joker Swaps! 💎',
    roomTimeLeft: 'Time Left',
    roomCalculating: 'Calculating...',
    roomExposureMeter: 'Exposure Meter',
    roomExpNoEntry: 'Upload your photo to start and receive 10 baseline energy!',
    roomExpNewPhotos: '⚡ New photo arrived in the Arena (or someone used a Joker)! Rate it to keep your meter maxed out!',
    roomExpMaxed: '🔥 Your photo is at peak visibility! Currently no more images to review in the Arena.',
    roomVotingArena: '⚔️ Review Arena',
    roomNoVoteRight: 'No Voting Rights!',
    roomNoVoteRightDesc: 'To enter the battle, you must first submit your own photo!',
    roomAllVoted: 'You reviewed everything!',
    roomAllVotedDesc: 'Wait for others to upload new pictures.',
    roomOffTopicWarning: '⚠️ {count} players flag this image as Off-Topic or AI generated!',
    roomMasterVoteBtn: '👑 Master Special Award (+10 points)',
    roomMasterVotesRemaining: '{count} master votes remaining',
    roomVoteSuper: '✨ Super',
    roomPoints: ' points',
    roomVoteBrilliant: '🔥 Brilliant',
    roomVotePass: '⏭️ Skip (0 points)',
    roomReportBtn: '⚠️ Report Off-Topic / AI Suspect',
    roomLoadingPhoto: 'Loading photo...',
    roomMyEntry: '📸 My Submission',
    roomJokerSwaps: 'Joker swaps: {count}',
    roomYouAreMaster: 'You are the Challenge Master!',
    roomYouAreMasterDesc: 'You have been appointed Challenge Master for this match! You cannot compete with your own work, but you receive 5 exclusive Special Awards worth +10 points each to distribute among your favorite pictures.',
    roomResult: 'Score',
    roomViews: 'Views',
    roomMyOffTopicTitle: '🚫 Warning: Off-Topic Suspect!',
    roomMyOffTopicDesc: 'Your photo has been reported as off-topic or AI-generated by {count} of your peers. Please adhere strictly to the theme and avoid AI-generated images!',
    roomSwapTitle: '🔄 Upload New Photo & Swap',
    roomSwapDesc: 'Not going well? Upload a brand new photo for 1 swap point! Your new image starts at 0 points, but you won\'t lose your current one either.',
    roomSwappingInProgress: 'Swapping...',
    roomSwapBrowseBtn: 'Spend Joker by Browsing 🔄',
    roomOrUseAlbum: 'OR use 1 Joker on an existing album photo:',
    roomLoadingGallery: '⏳ Loading gallery...',
    roomSwapGalleryBtn: '🖼️ Joker Swap from Arena Gallery',
    roomNoSwapsLeft: '🔒 Out of global Joker swaps! Perform well in tasks for extra points.',
    roomPastEntriesTitle: '↩️ Your previous entries in this round',
    roomPastSavedScore: 'Saved previous standing:',
    roomReactivateBtn: '↩️ Reactivate',
    roomUploadingInProgress: 'Uploading...',
    roomUploadSubmitBtn: 'Submit & Enter 🚀',
    roomOrChooseAlbumUpload: 'OR choose an existing photo from your album:',
    roomChooseGalleryUploadBtn: '🖼️ Choose from Arena Gallery',
    roomClubLeague: '🛡️ Clubs League',
    roomLiveBadge: 'LIVE',
    roomClubLeagueDesc: 'Based on the performance of the top 3 club members.',
    roomNoClubsYet: 'No clubs ranked yet.',
    roomActiveMembers: 'active members',
    roomBlindLeaderboard: '🏆 Blind Leaderboard',
    roomBlindLeaderboardDesc: 'Opponent identities are hidden to prevent tactical voting!',
    roomArenaEmpty: 'The Arena is currently empty.',
    roomEncryptedOpponent: 'Encrypted Opponent',
    roomMe: 'Me',

    // === EN BLOKK ALJA ===
    planTitle: '📜 Propose New Challenge',
    planDesc: 'Outline the challenge! After approval, your proposal will be included in the official upcoming challenges.',
    planLabelTitle: 'Challenge Name (Theme) *',
    planPlaceholderTitle: 'E.g., Roar of Wild Waters, City Silhouettes',
    planLabelDesc: 'Mission Orders (Detailed Description & Constraints) *',
    planPlaceholderDesc: 'What kind of compositions are you expecting? What is forbidden to use?',
    planLabelStart: 'Start Date *',
    planLabelEnd: 'End Date *',
    planLabelMaster: 'Designated Challenge Master',
    planPlaceholderMaster: 'E.g., Mary Smith',
    planLabelAuthor: 'Cover Photo Creator',
    planPlaceholderAuthor: 'E.g., John Doe',
    planLabelCover: 'Select Cover Photo',
    planPreviewAlt: 'Preview',
    planSubmitting: 'Submitting proposal...',
    planSubmitBtn: 'Submit Proposal for Club Review ⚔️',
    msgFillAllFields: 'Please fill in all required fields!',
    msgProposalSuccess: '⚔️ Challenge proposal successfully submitted for review!',
    msgProposalError: 'An error occurred during submission.',

    // === EN BLOKK ALJA ===
    hofLoading: '⏳ Assembling the podium...',
    hofEmpty: 'No photographers have earned points yet. Be the first!',
    hofTitle: '👑 Global Photographers Hall of Fame',
    hofDesc: 'The community\'s cumulative leaderboard based on stars earned in active and completed arenas.',
    hofYou: 'YOU',

    // === EN BLOKK ALJA ===
    archiveTitle: '📜 Completed Challenges',
    archiveNotice: 'Click on the photo in the results to like or comment',
    archiveEmpty: 'No completed matches.',
    archiveCoverAuthor: '📸 Cover photo by: ',
    archiveClubLeague: '🛡️ Clubs League Results',
    archiveBlitz: 'Blitz Match',
    archiveMaster: 'Master Match',
    archiveClubLeagueDesc: 'Based on the performance of the top 3 members.',
    archiveNoClubs: 'No clubs competed in this match.',
    archiveSelectChallenge: 'Select a challenge from the left sidebar.',
    archiveUnknownClub: 'Unknown Club',
    archiveBasedOnPoints: ' based on points of photographers',
    archiveMemberIndividualScore: '📊 Members individual score ({count} people)',
    archiveNoMemberPoints: 'No one earned points from this club.',
    archiveIndividualRanking: '🏅 Individual Ranking',
    archiveSelectMatch: 'Select a match to view results.',
    archivePhotographer: 'Photographer',
    archivePostPraises: ' post-match praises',
    archiveNomadWarrior: 'Nomad warrior',

    // === EN BLOKK ALJA ===
    trophyLoading: '⏳ Loading statistics...',
    trophyError: 'Failed to load data.',
    trophyCurrentStatus: 'Your Current Status',
    trophyLegendMax: 'You have reached the highest rank! You are the club\'s Visual Legend! 👑',
    trophyNextLevelPoints: 'Another {points} points required for the next level!',
    trophyNextLevelWins: '🔒 You have the points, but another {wins} Arena Victory (🥇) is required to level up!',
    trophyNextLevelReady: 'Congratulations! All conditions met to level up!',
    trophyPremiumActive: 'Active Victory Premium Membership!',
    trophyPremiumDesc: 'As an Arena champion, your unlimited premium privileges are secured until: ',
    trophyPremiumNotice: ' (No credit card required).',
    trophyStatTotalPoints: 'Total Points Earned',
    trophyStatWins: 'Arena Victories (🥇)',
    trophyStatPodiums: 'Podium (2nd-3rd place)',
    trophyStatJokers: 'Available Joker Swaps',
    trophyStatViews: 'Total Views',
    trophyInviteTitle: '🎁 Invite a Friend!',
    trophyInviteDesc: 'Share your code with a fellow photographer! If they register on the portal AND enter your code, you instantly receive +10 global Joker swaps.',
    trophyInviteCode: 'YOUR CODE:',
    trophyCopy: 'Copy',
    trophyCopiedAlert: '📋 Invitation code copied to clipboard!',
    trophyReferredTitle: '🤝 Who invited you?',
    trophyReferredDesc: 'If you registered on the Photo Club Portal via a friend\'s recommendation, enter their personal code so they receive their well-deserved reward swaps!',
    trophyReferredSuccess: '✓ Successfully registered your invitation! Thank you.',
    trophySubmit: 'Submit',
    trophyPlaceholderRef: 'E.g., REF-A1B2C3',
    trophyPastEntries: '📸 Past Submissions ({count})',
    trophyNoPastEntries: 'No completed challenges yet!',
    trophyNoPastEntriesDesc: 'Participate in challenges, and your past results will be displayed here.',
    trophyBadge1st: '🥇 1st Place',
    trophyBadgePodium: '🏆 Podium (2nd-3rd)',
    trophyField: 'Field: {count} photos',
    trophyRankLabel: 'Rank: ',
    trophyShareBtn: '🚀 Share Result',
    trophyPointsUnit: ' points',

    // === EN BLOKK ALJA ===
    modalUploadTitle: '🖼️ Entry from Arena Gallery',
    modalSwapTitle: '🃏 Choose Your Joker Photo',
    modalUploadDesc: 'Which existing gallery photo would you like to enter into the current match?',
    modalSwapDesc: 'Which gallery image are you sending into battle? Blue-bordered rollbacks keep their previously earned stars in this round!',
    modalBadgeSwapBack: '↩️ Rollback',
    msgUploadConfirm: 'Are you sure you want to enter the match with this existing photo?',
    msgUploadSuccess: '🎉 Successfully entered from album!',
    msgUploadError: 'An error occurred during entry.'
  }
};

type Language = 'hu' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof typeof translations.hu) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // 🎯 JAVÍTVA: Ha nincs elmentve semmi, kényszerítve a magyar (hu) az alapértelmezett!
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    if (saved === 'hu' || saved === 'en') return saved;
    return 'hu'; 
  });

  const setLang = (newLang: Language) => {
    localStorage.setItem('app_lang', newLang);
    setLangState(newLang);
  };

  const t = (key: keyof typeof translations.hu) => {
    return translations[lang]?.[key] || translations['hu'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
